### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/unocss-typescript-dsl#34]
## todo

- [x] export runtime from a package and provide types by generating `.d.ts`
  - https://github.com/hi-ogawa/unocss-typescript-dsl/pull/32
- [ ] improve transform
  - js token, strip literal before regex?
  - rollup parser?

## todo (chore)

- [x] rename to `unocss-ts`
- [x] stackblitz demo
- [x] cleanup readme
- [x] replace `vm` with `eval`
- [x] improve magic-string
  - https://github.com/hi-ogawa/unocss-typescript-dsl/pull/31
- [x] fix `dependencies` and `peerDependencies`
  - https://github.com/hi-ogawa/unocss-typescript-dsl/pull/33
- [x] re-bump cli
  - https://github.com/hi-ogawa/unocss-typescript-dsl/pull/32
