### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hi-ogawa** [hi-ogawa/unocss-typescript-dsl#4]
## to workaround

- [x] some classes are not generated properly, which might be likely due to unocss doesn't have autocomplete defined e.g.
  - `border`
  - `w-full`, `w-6`
    - `full` handling is defined in https://github.com/unocss/unocss/blob/f1957bfbd70aa8ffc8dcb57da36771b7af7ab2dd/packages/preset-mini/src/_utils/handlers/handlers.ts#L86
  - `opacity-`
  - `transition`
  - `aria`
  - fixed by https://github.com/hi-ogawa/unocss-typescript-dsl/pull/7
 
## to fix

- [x] handle `DEFAULT` (e.g. `blue_DEFAULT` should be just `blue`)
  - https://github.com/unocss/unocss/blob/f1957bfbd70aa8ffc8dcb57da36771b7af7ab2dd/packages/preset-mini/src/_theme/colors.ts#L339
- [x] handle `prefix` config
- [ ] don't emit unused typing

## feature

- jsdoc
  - typewind adds corresponding css in each property https://github.com/Mokshit06/typewind/blob/cdaf58c1fdc168970b2e89840ca6f5b7d91b3175/packages/typewind/src/cli.ts#L8
- perf ((EDIT: added `--filter-colors` options and it looks effective enough)
    - default theme leads too many combination and slows down entire completion
    - probably allow culling certain theme enum manually
    - it might be better to expand "interpolated" literal type into simpler ones
      - e.g. `${"m" | "p"}${"t" | "b"}-${"0" | "1"}` => `"mt-0" | "mt-1" | ... `
- ~declaration merging to allow overriding quickly locally~
- making things more configurable https://github.com/hi-ogawa/unocss-typescript-dsl/blob/491347657dd60b7fb7e24678d838bc6da63f4df0/src/runtime.ts#L3-L7

## chore

- [x] integration test
- [x] update README.md
- [x] organize packages
